import type { Metadata } from "next";
import "./globals.css";
import { Providers, CustomMainPageLayout } from "./providers/";
import Header from "@/components/navBar/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full bg-[#e0f1d8] w-full">
      <body className="h-full w-full flex flex-col ">
        <Providers>
          <Header />
          <CustomMainPageLayout>{children}</CustomMainPageLayout>
        </Providers>
      </body>
    </html>
  );
}
