spring:
  jpa:
    show-sql: true
  config:
    import:
      - optional:file:./.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev
logging:
  level:
    "[org.springframework.security]": DEBUG
server:
  port: 8080
jwt:
  secret: ${SECRET_APP}
  expiration-ms: ${JWT_EXPIRATION_MS}
