name: build_pipeline

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-puh:
        runs-on: ubuntu-latest
        environment: CERT

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
# todo: add tests later
          

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1

          - name: logging to AWS
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build with Maven
            run: |
              chmod +x springboot-Projectg/mvnw
              cd springboot-Projectg
              ./mvnw clean package

          - name: build and push Docker image to ECR
            id: build-image
            env:
              ECR_REGISTRY: 125273094628.dkr.ecr.us-east-1.amazonaws.com
              ECR_REPOSITORY: springboot_project
              IMAGE_TAG: ${{ github.sha }}
            run: |
              docker build -t ecommerce ./springboot-Projectg
              docker tag ecommerce:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
              
          - name: Fill in the new image ID in the Amazon ECS task definition
            id: task-defintnion
            uses: aws-actions/amazon-ecs-deploy-task-definition@v2
            with:
              task-definition: task-definition.json
              container-name: ecommerce-api
              image: ${{ steps.build-image.outputs.image }}
              wait-for-service-stability: true
              cluster: ecommerce-dev-database
              service: ecommerce-dev-task-2-service